export const countries = [
  { type: 'afghanistan', name: 'Afghanistan, Kabul' },
  { type: 'albania', name: 'Albania, Tirana' },
  { type: 'algeria', name: 'Algeria, Algiers' },
  { type: 'andorra', name: 'Andorra, Andorra la Vella' },
  { type: 'angola', name: 'Angola, Luanda' },
  { type: 'antigua_and_barbuda', name: "Antigua and Barbuda, St. John's" },
  { type: 'argentina', name: 'Argentina, Buenos Aires' },
  { type: 'armenia', name: 'Armenia, Yerevan' },
  { type: 'australia', name: 'Australia, Canberra' },
  { type: 'austria', name: 'Austria, Vienna' },
  { type: 'azerbaijan', name: 'Azerbaijan, Baku' },
  { type: 'bahamas', name: 'Bahamas, Nassau' },
  { type: 'bahrain', name: 'Bahrain, Manama' },
  { type: 'bangladesh', name: 'Bangladesh, Dhaka' },
  { type: 'barbados', name: 'Barbados, Bridgetown' },
  { type: 'belarus', name: 'Belarus, Minsk' },
  { type: 'belgium', name: 'Belgium, Brussels' },
  { type: 'belize', name: 'Belize, Belmopan' },
  { type: 'benin', name: 'Benin, Porto-Novo' },
  { type: 'bhutan', name: 'Bhutan, Thimphu' },
  { type: 'bolivia', name: 'Bolivia, Sucre' },
  { type: 'bosnia_and_herzegovina', name: 'Bosnia and Herzegovina, Sarajevo' },
  { type: 'botswana', name: 'Botswana, Gaborone' },
  { type: 'brazil', name: 'Brazil, Brasília' },
  { type: 'brunei', name: 'Brunei, Bandar Seri Begawan' },
  { type: 'bulgaria', name: 'Bulgaria, Sofia' },
  { type: 'burkina_faso', name: 'Burkina Faso, Ouagadougou' },
  { type: 'burundi', name: 'Burundi, Gitega' },
  { type: 'cabo_verde', name: 'Cabo Verde, Praia' },
  { type: 'cambodia', name: 'Cambodia, Phnom Penh' },
  { type: 'cameroon', name: 'Cameroon, Yaoundé' },
  { type: 'canada', name: 'Canada, Ottawa' },
  { type: 'central_african_republic', name: 'Central African Republic, Bangui' },
  { type: 'chad', name: "Chad, N'Djamena" },
  { type: 'chile', name: 'Chile, Santiago' },
  { type: 'china', name: 'China, Beijing' },
  { type: 'colombia', name: 'Colombia, Bogotá' },
  { type: 'comoros', name: 'Comoros, Moroni' },
  { type: 'congo', name: 'Congo, Brazzaville' },
  { type: 'congo_democratic_republic', name: 'Democratic Republic of the Congo, Kinshasa' },
  { type: 'costa_rica', name: 'Costa Rica, San José' },
  { type: 'croatia', name: 'Croatia, Zagreb' },
  { type: 'cuba', name: 'Cuba, Havana' },
  { type: 'cyprus', name: 'Cyprus, Nicosia' },
  { type: 'czech_republic', name: 'Czech Republic, Prague' },
  { type: 'denmark', name: 'Denmark, Copenhagen' },
  { type: 'djibouti', name: 'Djibouti, Djibouti' },
  { type: 'dominica', name: 'Dominica, Roseau' },
  { type: 'dominican_republic', name: 'Dominican Republic, Santo Domingo' },
  { type: 'ecuador', name: 'Ecuador, Quito' },
  { type: 'egypt', name: 'Egypt, Cairo' },
  { type: 'el_salvador', name: 'El Salvador, San Salvador' },
  { type: 'equatorial_guinea', name: 'Equatorial Guinea, Malabo' },
  { type: 'eritrea', name: 'Eritrea, Asmara' },
  { type: 'estonia', name: 'Estonia, Tallinn' },
  { type: 'eswatini', name: 'Eswatini, Mbabane' },
  { type: 'ethiopia', name: 'Ethiopia, Addis Ababa' },
  { type: 'fiji', name: 'Fiji, Suva' },
  { type: 'finland', name: 'Finland, Helsinki' },
  { type: 'france', name: 'France, Paris' },
  { type: 'gabon', name: 'Gabon, Libreville' },
  { type: 'gambia', name: 'Gambia, Banjul' },
  { type: 'georgia', name: 'Georgia, Tbilisi' },
  { type: 'germany', name: 'Germany, Berlin' },
  { type: 'ghana', name: 'Ghana, Accra' },
  { type: 'greece', name: 'Greece, Athens' },
  { type: 'grenada', name: "Grenada, St. George's" },
  { type: 'guatemala', name: 'Guatemala, Guatemala City' },
  { type: 'guinea', name: 'Guinea, Conakry' },
  { type: 'guinea_bissau', name: 'Guinea-Bissau, Bissau' },
  { type: 'guyana', name: 'Guyana, Georgetown' },
  { type: 'haiti', name: 'Haiti, Port-au-Prince' },
  { type: 'honduras', name: 'Honduras, Tegucigalpa' },
  { type: 'hungary', name: 'Hungary, Budapest' },
  { type: 'iceland', name: 'Iceland, Reykjavik' },
  { type: 'india', name: 'India, New Delhi' },
  { type: 'indonesia', name: 'Indonesia, Jakarta' },
  { type: 'iran', name: 'Iran, Tehran' },
  { type: 'iraq', name: 'Iraq, Baghdad' },
  { type: 'ireland', name: 'Ireland, Dublin' },
  { type: 'israel', name: 'Israel, Jerusalem' },
  { type: 'italy', name: 'Italy, Rome' },
  { type: 'jamaica', name: 'Jamaica, Kingston' },
  { type: 'japan', name: 'Japan, Tokyo' },
  { type: 'jordan', name: 'Jordan, Amman' },
  { type: 'kazakhstan', name: 'Kazakhstan, Nur-Sultan' },
  { type: 'kenya', name: 'Kenya, Nairobi' },
  { type: 'kiribati', name: 'Kiribati, Tarawa' },
  { type: 'korea_north', name: 'North Korea, Pyongyang' },
  { type: 'korea_south', name: 'South Korea, Seoul' },
  { type: 'kuwait', name: 'Kuwait, Kuwait City' },
  { type: 'kyrgyzstan', name: 'Kyrgyzstan, Bishkek' },
  { type: 'laos', name: 'Laos, Vientiane' },
  { type: 'latvia', name: 'Latvia, Riga' },
  { type: 'lebanon', name: 'Lebanon, Beirut' },
  { type: 'lesotho', name: 'Lesotho, Maseru' },
  { type: 'liberia', name: 'Liberia, Monrovia' },
  { type: 'libya', name: 'Libya, Tripoli' },
  { type: 'liechtenstein', name: 'Liechtenstein, Vaduz' },
  { type: 'lithuania', name: 'Lithuania, Vilnius' },
  { type: 'luxembourg', name: 'Luxembourg, Luxembourg' },
  { type: 'madagascar', name: 'Madagascar, Antananarivo' },
  { type: 'malawi', name: 'Malawi, Lilongwe' },
  { type: 'malaysia', name: 'Malaysia, Kuala Lumpur' },
  { type: 'maldives', name: 'Maldives, Malé' },
  { type: 'mali', name: 'Mali, Bamako' },
  { type: 'malta', name: 'Malta, Valletta' },
  { type: 'marshall_islands', name: 'Marshall Islands, Majuro' },
  { type: 'mauritania', name: 'Mauritania, Nouakchott' },
  { type: 'mauritius', name: 'Mauritius, Port Louis' },
  { type: 'mexico', name: 'Mexico, Mexico City' },
  { type: 'micronesia', name: 'Micronesia, Palikir' },
  { type: 'moldova', name: 'Moldova, Chișinău' },
  { type: 'monaco', name: 'Monaco, Monaco' },
  { type: 'mongolia', name: 'Mongolia, Ulaanbaatar' },
  { type: 'montenegro', name: 'Montenegro, Podgorica' },
  { type: 'morocco', name: 'Morocco, Rabat' },
  { type: 'mozambique', name: 'Mozambique, Maputo' },
  { type: 'myanmar', name: 'Myanmar, Naypyidaw' },
  { type: 'namibia', name: 'Namibia, Windhoek' },
  { type: 'nauru', name: 'Nauru, Yaren District' },
  { type: 'nepal', name: 'Nepal, Kathmandu' },
  { type: 'netherlands', name: 'Netherlands, Amsterdam' },
  { type: 'new_zealand', name: 'New Zealand, Wellington' },
  { type: 'nicaragua', name: 'Nicaragua, Managua' },
  { type: 'niger', name: 'Niger, Niamey' },
  { type: 'nigeria', name: 'Nigeria, Abuja' },
  { type: 'north_macedonia', name: 'North Macedonia, Skopje' },
  { type: 'norway', name: 'Norway, Oslo' },
  { type: 'oman', name: 'Oman, Muscat' },
  { type: 'pakistan', name: 'Pakistan, Islamabad' },
  { type: 'palau', name: 'Palau, Ngerulmud' },
  { type: 'panama', name: 'Panama, Panama City' },
  { type: 'papua_new_guinea', name: 'Papua New Guinea, Port Moresby' },
  { type: 'paraguay', name: 'Paraguay, Asunción' },
  { type: 'peru', name: 'Peru, Lima' },
  { type: 'philippines', name: 'Philippines, Manila' },
  { type: 'poland', name: 'Poland, Warsaw' },
  { type: 'portugal', name: 'Portugal, Lisbon' },
  { type: 'qatar', name: 'Qatar, Doha' },
  { type: 'romania', name: 'Romania, Bucharest' },
  { type: 'russia', name: 'Russia, Moscow' },
  { type: 'rwanda', name: 'Rwanda, Kigali' },
  { type: 'saint_kitts_and_nevis', name: 'Saint Kitts and Nevis, Basseterre' },
  { type: 'saint_lucia', name: 'Saint Lucia, Castries' },
  { type: 'saint_vincent_and_the_grenadines', name: 'Saint Vincent and the Grenadines, Kingstown' },
  { type: 'samoa', name: 'Samoa, Apia' },
  { type: 'san_marino', name: 'San Marino, San Marino' },
  { type: 'sao_tome_and_principe', name: 'São Tomé and Príncipe, São Tomé' },
  { type: 'saudi_arabia', name: 'Saudi Arabia, Riyadh' },
  { type: 'senegal', name: 'Senegal, Dakar' },
  { type: 'serbia', name: 'Serbia, Belgrade' },
  { type: 'seychelles', name: 'Seychelles, Victoria' },
  { type: 'sierra_leone', name: 'Sierra Leone, Freetown' },
  { type: 'singapore', name: 'Singapore, Singapore' },
  { type: 'slovakia', name: 'Slovakia, Bratislava' },
  { type: 'slovenia', name: 'Slovenia, Ljubljana' },
  { type: 'solomon_islands', name: 'Solomon Islands, Honiara' },
  { type: 'somalia', name: 'Somalia, Mogadishu' },
  { type: 'south_africa', name: 'South Africa, Pretoria' },
  { type: 'south_sudan', name: 'South Sudan, Juba' },
  { type: 'spain', name: 'Spain, Madrid' },
  { type: 'sri_lanka', name: 'Sri Lanka, Sri Jayawardenepura Kotte' },
  { type: 'sudan', name: 'Sudan, Khartoum' },
  { type: 'suriname', name: 'Suriname, Paramaribo' },
  { type: 'sweden', name: 'Sweden, Stockholm' },
  { type: 'switzerland', name: 'Switzerland, Bern' },
  { type: 'syria', name: 'Syria, Damascus' },
  { type: 'taiwan', name: 'Taiwan, Taipei' },
  { type: 'tajikistan', name: 'Tajikistan, Dushanbe' },
  { type: 'tanzania', name: 'Tanzania, Dodoma' },
  { type: 'thailand', name: 'Thailand, Bangkok' },
  { type: 'timor_leste', name: 'Timor-Leste, Dili' },
  { type: 'togo', name: 'Togo, Lomé' },
  { type: 'tonga', name: 'Tonga, Nukuʻalofa' },
  { type: 'trinidad_and_tobago', name: 'Trinidad and Tobago, Port of Spain' },
  { type: 'tunisia', name: 'Tunisia, Tunis' },
  { type: 'turkey', name: 'Turkey, Ankara' },
  { type: 'turkmenistan', name: 'Turkmenistan, Ashgabat' },
  { type: 'tuvalu', name: 'Tuvalu, Funafuti' },
  { type: 'uganda', name: 'Uganda, Kampala' },
  { type: 'ukraine', name: 'Ukraine, Kyiv' },
  { type: 'united_arab_emirates', name: 'United Arab Emirates, Abu Dhabi' },
  { type: 'united_kingdom', name: 'United Kingdom, London' },
  { type: 'united_states', name: 'United States, Washington, D.C.' },
  { type: 'uruguay', name: 'Uruguay, Montevideo' },
  { type: 'uzbekistan', name: 'Uzbekistan, Tashkent' },
  { type: 'vanuatu', name: 'Vanuatu, Port Vila' },
  { type: 'vatican_city', name: 'Vatican City, Vatican City' },
  { type: 'venezuela', name: 'Venezuela, Caracas' },
  { type: 'vietnam', name: 'Vietnam, Hanoi' },
  { type: 'yemen', name: "Yemen, Sana'a" },
  { type: 'zambia', name: 'Zambia, Lusaka' },
  { type: 'zimbabwe', name: 'Zimbabwe, Harare' },
]
