export const languageTools = [
  { name: 'all', type: 'All Tools' },
  { name: 'nextjs', type: 'Next.js' },
  { name: 'reactjs', type: 'React.js' },
  { name: 'vuejs', type: 'Vue.js' },
  { name: 'angular', type: 'Angular' },
  { name: 'svelte', type: 'Svelte' },
  { name: 'typescript', type: 'TypeScript' },
  { name: 'javascript', type: 'JavaScript' },
  { name: 'gatsby', type: 'Gatsby' },
  { name: 'solidjs', type: 'Solid.js' },
  { name: 'preact', type: 'Preact' },
  { name: 'ember', type: 'Ember.js' },
  { name: 'backbone', type: 'Backbone.js' },
  { name: 'lit', type: 'Lit' },
  { name: 'alpinejs', type: 'Alpine.js' },
  { name: 'stencil', type: 'Stencil' },
]
