export const logos = [
  { src: 'https://cdn.worldvectorlogo.com/logos/logo-javascript.svg', alt: 'JavaScript' },
  { src: 'https://img.icons8.com/fluent-systems-filled/512/FFFFFF/nextjs.png', alt: 'Next.Js' },
  { src: 'https://astro.build/assets/press/astro-icon-light-gradient.svg', alt: 'Astro' },
  { src: 'https://cdn.worldvectorlogo.com/logos/typescript.svg', alt: 'TypeScript' },
  { src: 'https://cdn.worldvectorlogo.com/logos/react-2.svg', alt: 'React' },
  { src: 'https://ui.shadcn.com/apple-touch-icon.png', alt: 'shadcn/ui' },
  { src: 'https://avatars.githubusercontent.com/u/166878038?s=200&v=4', alt: 'Magic UI' },
  { src: 'https://nuxt.com/assets/design-kit/icon-green.svg', alt: 'Nuxt.js' },
  { src: 'https://cdn.worldvectorlogo.com/logos/vue-9.svg', alt: 'Vue.js' },
  { src: 'https://cdn.worldvectorlogo.com/logos/framer-motion.svg', alt: 'Framer Motion' },
  { src: 'https://cdn.worldvectorlogo.com/logos/css-3.svg', alt: 'CSS' },
  { src: 'https://cdn.worldvectorlogo.com/logos/logo-javascript.svg', alt: 'JavaScript' },
  { src: 'https://img.icons8.com/fluent-systems-filled/512/FFFFFF/nextjs.png', alt: 'Next.Js' },
  { src: 'https://astro.build/assets/press/astro-icon-light-gradient.svg', alt: 'Astro' },
  { src: 'https://cdn.worldvectorlogo.com/logos/typescript.svg', alt: 'TypeScript' },
  { src: 'https://cdn.worldvectorlogo.com/logos/react-2.svg', alt: 'React' },
  { src: 'https://ui.shadcn.com/apple-touch-icon.png', alt: 'shadcn/ui' },
  { src: 'https://avatars.githubusercontent.com/u/166878038?s=200&v=4', alt: 'Magic UI' },
  { src: 'https://nuxt.com/assets/design-kit/icon-green.svg', alt: 'Nuxt.js' },
  { src: 'https://cdn.worldvectorlogo.com/logos/vue-9.svg', alt: 'Vue.js' },
  { src: 'https://cdn.worldvectorlogo.com/logos/framer-motion.svg', alt: 'Framer Motion' },
  { src: 'https://cdn.worldvectorlogo.com/logos/css-3.svg', alt: 'CSS' },
]
