export const roles = [
  { type: 'Design', name: 'Product Designer' },
  { type: 'Engineering', name: 'Software Engineer' },
  { type: 'Product', name: 'Product Manager' },
  { type: 'Data', name: 'Data Scientist' },
  { type: 'Design', name: 'UX Designer' },
  { type: 'Marketing', name: 'Marketing Specialist' },
  { type: 'Finance', name: 'Financial Analyst' },
  { type: 'Operations', name: 'Operations Manager' },
  { type: 'Sales', name: 'Sales Representative' },
  { type: 'HR', name: 'HR Specialist' },
  { type: 'Engineering', name: 'Frontend Developer' },
  { type: 'Engineering', name: 'Backend Developer' },
  { type: 'Engineering', name: 'Full Stack Developer' },
  { type: 'Engineering', name: 'DevOps Engineer' },
  { type: 'Data', name: 'Data Analyst' },
  { type: 'Data', name: 'Machine Learning Engineer' },
  { type: 'Customer Support', name: 'Customer Support Specialist' },
  { type: 'Customer Success', name: 'Customer Success Manager' },
  { type: 'Legal', name: 'Legal Counsel' },
  { type: 'Content', name: 'Content Writer' },
  { type: 'Content', name: 'SEO Specialist' },
  { type: 'Project Management', name: 'Project Manager' },
  { type: 'Sales', name: 'Account Manager' },
  { type: 'IT', name: 'IT Support Specialist' },
  { type: 'Administration', name: 'Administrative Assistant' },
  { type: 'Marketing', name: 'Social Media Manager' },
  { type: 'Marketing', name: 'Brand Manager' },
  { type: 'Design', name: 'Graphic Designer' },
  { type: 'Finance', name: 'Accountant' },
  { type: 'Finance', name: 'Financial Planner' },
  { type: 'Engineering', name: 'Quality Assurance Engineer' },
  { type: 'Engineering', name: 'Systems Architect' },
  { type: 'Engineering', name: 'Mobile Developer' },
  { type: 'Engineering', name: 'Embedded Systems Engineer' },
  { type: 'Product', name: 'Product Owner' },
  { type: 'Product', name: 'Scrum Master' },
  { type: 'Product', name: 'Business Analyst' },
  { type: 'Data', name: 'Data Engineer' },
  { type: 'Data', name: 'Business Intelligence Analyst' },
  { type: 'Customer Success', name: 'Onboarding Specialist' },
  { type: 'Customer Support', name: 'Technical Support Engineer' },
  { type: 'Legal', name: 'Compliance Specialist' },
  { type: 'Legal', name: 'Paralegal' },
  { type: 'Content', name: 'Copywriter' },
  { type: 'Content', name: 'Content Strategist' },
  { type: 'Marketing', name: 'Digital Marketing Specialist' },
  { type: 'Marketing', name: 'Email Marketing Manager' },
  { type: 'Marketing', name: 'Growth Marketer' },
  { type: 'Finance', name: 'Controller' },
  { type: 'Finance', name: 'Treasury Analyst' },
  { type: 'HR', name: 'Recruiter' },
  { type: 'HR', name: 'Talent Acquisition Specialist' },
  { type: 'Operations', name: 'Logistics Coordinator' },
  { type: 'Operations', name: 'Supply Chain Manager' },
  { type: 'Administration', name: 'Office Manager' },
  { type: 'IT', name: 'Network Administrator' },
  { type: 'IT', name: 'System Administrator' },
  { type: 'Engineering', name: 'Cybersecurity Specialist' },
  { type: 'Sales', name: 'Business Development Representative' },
  { type: 'Sales', name: 'Sales Engineer' },
  { type: 'Sales', name: 'Inside Sales Representative' },
]
