export const roles = [
  { type: 'Design1', name: 'Product Designer' },
  { type: 'Engineering1', name: 'Software Engineer' },
  { type: 'Product1', name: 'Product Manager' },
  { type: 'Data1', name: 'Data Scientist' },
  { type: 'Design2', name: 'UX Designer' },
  { type: 'Marketing5', name: 'Marketing Specialist' },
  { type: 'Finance1', name: 'Financial Analyst' },
  { type: 'Operations', name: 'Operations Manager' },
  { type: 'Sales4', name: 'Sales Representative' },
  { type: 'HR9', name: 'HR Specialist' },
  { type: 'Engineering2', name: 'Frontend Developer' },
  { type: 'Engineering3', name: 'Backend Developer' },
  { type: 'Engineering4', name: 'Full Stack Developer' },
  { type: 'Engineering5', name: 'DevOps Engineer' },
  { type: 'Data2', name: 'Data Analyst' },
  { type: 'Data3', name: 'Machine Learning Engineer' },
  { type: 'Customer Support1', name: 'Customer Support Specialist' },
  { type: 'Customer Success2', name: 'Customer Success Manager' },
  { type: 'Legal1', name: 'Legal Counsel' },
  { type: 'Content1', name: 'Content Writer' },
  { type: 'Content2', name: 'SEO Specialist' },
  { type: 'Project Management', name: 'Project Manager' },
  { type: 'Sales5', name: 'Account Manager' },
  { type: 'IT', name: 'IT Support Specialist' },
  { type: 'Administration4', name: 'Administrative Assistant' },
  { type: 'Marketing6', name: 'Social Media Manager' },
  { type: 'Marketing7', name: 'Brand Manager' },
  { type: 'Design3', name: 'Graphic Designer' },
  { type: 'Finance2', name: 'Accountant' },
  { type: 'Finance3', name: 'Financial Planner' },
  { type: 'Engineering6', name: 'Quality Assurance Engineer' },
  { type: 'Engineering7', name: 'Systems Architect' },
  { type: 'Engineering8', name: 'Mobile Developer' },
  { type: 'Engineering9', name: 'Embedded Systems Engineer' },
  { type: 'Product2', name: 'Product Owner' },
  { type: 'Product3', name: 'Scrum Master' },
  { type: 'Product4', name: 'Business Analyst' },
  { type: 'Data4', name: 'Data Engineer' },
  { type: 'Data5', name: 'Business Intelligence Analyst' },
  { type: 'Customer Success3', name: 'Onboarding Specialist' },
  { type: 'Customer Support4', name: 'Technical Support Engineer' },
  { type: 'Legal9', name: 'Compliance Specialist' },
  { type: 'Legal8', name: 'Paralegal' },
  { type: 'Content3', name: 'Copywriter' },
  { type: 'Content4', name: 'Content Strategist' },
  { type: 'Marketing1', name: 'Digital Marketing Specialist' },
  { type: 'Marketing2', name: 'Email Marketing Manager' },
  { type: 'Marketing3', name: 'Growth Marketer' },
  { type: 'Finance4', name: 'Controller' },
  { type: 'Finance5', name: 'Treasury Analyst' },
  { type: 'HR1', name: 'Recruiter' },
  { type: 'HR2', name: 'Talent Acquisition Specialist' },
  { type: 'Operations1', name: 'Logistics Coordinator' },
  { type: 'Operations2', name: 'Supply Chain Manager' },
  { type: 'Administration5', name: 'Office Manager' },
  { type: 'IT1', name: 'Network Administrator' },
  { type: 'IT2', name: 'System Administrator' },
  { type: 'Engineering10', name: 'Cybersecurity Specialist' },
  { type: 'Sales1', name: 'Business Development Representative' },
  { type: 'Sales2', name: 'Sales Engineer' },
  { type: 'Sales3', name: 'Inside Sales Representative' },
]
