export interface Skill {
  name: string
  logo: string
  category: string
  level: string
  description: string
}

export const suggestedSkills: Skill[] = [
  // Frontend Frameworks and Libraries
  {
    name: 'React',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'JavaScript library for building user interfaces',
  },
  {
    name: 'Angular',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Platform for building web applications',
  },
  {
    name: 'Vue.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Progressive JavaScript framework',
  },
  {
    name: 'Next.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'React framework for production',
  },
  {
    name: 'Svelte',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Compiler for building user interfaces',
  },
  {
    name: 'Redux',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'State management for JavaScript apps',
  },
  {
    name: 'MobX',
    logo: 'https://mobx.js.org/assets/mobx.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple, scalable state management',
  },
  {
    name: 'Nuxt.js',
    logo: 'https://nuxtjs.org/design-kit/colored-logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Vue.js framework for server-side rendering',
  },
  {
    name: 'Ember.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ember/ember-original-wordmark.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Framework for ambitious web developers',
  },
  {
    name: 'Alpine.js',
    logo: 'https://alpinejs.dev/alpine_long.svg',
    category: 'Frontend',
    level: 'Beginner',
    description: 'Lightweight JavaScript framework',
  },
  {
    name: 'Lit',
    logo: 'https://lit.dev/images/flame-favicon.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple library for building web components',
  },
  {
    name: 'Astro',
    logo: 'https://astro.build/assets/press/astro-icon-light.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Static site builder for the modern web',
  },
  {
    name: 'Gatsby',
    logo: 'https://www.gatsbyjs.com/Gatsby-Monogram.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'React-based framework for building websites and apps',
  },
  // New additions
  {
    name: 'shadcn/ui',
    logo: 'https://ui.shadcn.com/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Re-usable components built using Radix UI and Tailwind CSS',
  },
  {
    name: 'Framer Motion',
    logo: 'https://framerusercontent.com/images/FwGRzdHhlF5dVX3w3adwXRyFz7U.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Production-ready motion library for React',
  },
  {
    name: 'React Hook Form',
    logo: 'https://avatars.githubusercontent.com/u/53986236?s=200&v=4',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Performant, flexible and extensible forms with easy-to-use validation',
  },
  {
    name: 'Zustand',
    logo: 'https://repository-images.githubusercontent.com/180328715/fca49300-e7f1-11ea-9f51-cfd949b31560',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Small, fast and scalable bearbones state-management solution',
  },
  {
    name: 'Storybook',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/storybook/storybook-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Tool for building UI components and pages in isolation',
  },
  {
    name: 'Vite',
    logo: 'https://vitejs.dev/logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Next generation frontend tooling',
  },
  {
    name: 'Remix',
    logo: 'https://remix.run/img/og.1.jpg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Full stack web framework based on React',
  },
  {
    name: 'Electron',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Framework for creating native applications with web technologies',
  },
  {
    name: 'jQuery',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Fast, small, and feature-rich JavaScript library',
  },
  {
    name: 'Backbone.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/backbonejs/backbonejs-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Give structure to web applications with models, views, and collections',
  },
  {
    name: 'Solid.js',
    logo: 'https://www.solidjs.com/assets/logo.123b04bc.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Declarative, efficient, and flexible JavaScript library for building user interfaces',
  },
  {
    name: 'Preact',
    logo: 'https://preactjs.com/assets/app-icon.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Fast 3kB alternative to React with the same modern API',
  },
  {
    name: 'Qwik',
    logo: 'https://qwik.builder.io/favicon.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Resumable JavaScript framework for building instant web applications',
  },
  {
    name: 'Stimulus',
    logo: 'https://stimulusjs.org/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Modest JavaScript framework for the HTML you already have',
  },
  {
    name: 'Mithril',
    logo: 'https://mithril.js.org/logo.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Modern client-side JavaScript framework for building Single Page Applications',
  },
  {
    name: 'Aurelia',
    logo: 'https://aurelia.io/styles/images/aurelia-icon.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'JavaScript client framework for mobile, desktop and web',
  },
  {
    name: 'Polymer',
    logo: 'https://www.polymer-project.org/images/logos/p-logo.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'JavaScript library for building web applications using Web Components',
  },
  {
    name: 'Ionic',
    logo: 'https://ionicframework.com/docs/icons/logo-ionic.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Open source UI toolkit for building performant, high-quality mobile and desktop apps',
  },
  {
    name: 'Windicss',
    logo: 'https://windicss.org/assets/logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Next generation utility-first CSS framework',
  },
  {
    name: 'UnoCSS',
    logo: 'https://raw.githubusercontent.com/unocss/unocss/main/playground/public/favicon.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Instant on-demand atomic CSS engine',
  },
  {
    name: 'Stitches',
    logo: 'https://stitches.dev/favicon.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS-in-JS with near-zero runtime, SSR, multi-variant support, and a best-in-class developer experience',
  },
  {
    name: 'Emotion',
    logo: 'https://emotion.sh/static/emotion.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS-in-JS library designed for high performance style composition',
  },
  {
    name: 'Playwright',
    logo: 'https://playwright.dev/img/playwright-logo.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Framework for Web Testing and Automation',
  },
  {
    name: 'Cypress',
    logo: 'https://www.cypress.io/images/layouts/navbar-brand.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'JavaScript End to End Testing Framework',
  },
  {
    name: 'Puppeteer',
    logo: 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol',
  },
  {
    name: 'TypeScript',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    category: 'Language',
    level: 'Advanced',
    description: 'Typed superset of JavaScript that compiles to plain JavaScript',
  },
  {
    name: 'Dart',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg',
    category: 'Language',
    level: 'Intermediate',
    description: 'Client-optimized language for fast apps on any platform',
  },
  {
    name: 'Elm',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elm/elm-original.svg',
    category: 'Language',
    level: 'Intermediate',
    description: 'A delightful language for reliable webapps',
  },
  {
    name: 'ReasonML',
    logo: 'https://reasonml.github.io/img/reason.svg',
    category: 'Language',
    level: 'Advanced',
    description: 'Syntax & toolchain for OCaml',
  },
  {
    name: 'PureScript',
    logo: 'https://pursuit.purescript.org/img/favicon.ico',
    category: 'Language',
    level: 'Advanced',
    description: 'A strongly-typed functional programming language that compiles to JavaScript',
  },
  {
    name: 'WebAssembly',
    logo: 'https://webassembly.org/css/webassembly.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Binary instruction format for a stack-based virtual machine',
  },
  {
    name: 'AssemblyScript',
    logo: 'https://www.assemblyscript.org/images/icon.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'TypeScript-like language that compiles to WebAssembly',
  },

  // Micro Frontends
  {
    name: 'Single-SPA',
    logo: 'https://single-spa.js.org/img/logo-white-bgblue.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Framework for bringing together multiple JavaScript microfrontends',
  },
  {
    name: 'Module Federation',
    logo: 'https://webpack.js.org/icon-pwa-512x512.d3dae4189855b3a72ff9.png',
    category: 'Frontend',
    level: 'Expert',
    description: 'Advanced webpack 5 feature enabling sharing of architecture',
  },

  // Static Site Generators
  {
    name: 'Hugo',
    logo: 'https://d33wubrfki0l68.cloudfront.net/c38c7334cc3f23585738e40334284fddcaf03d5e/2e17c/images/hugo-logo-wide.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Fast and flexible static site generator built with Go',
  },
  {
    name: '11ty',
    logo: 'https://www.11ty.dev/img/logo-github.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simpler static site generator for a more elegant web',
  },

  // Serverless and JAMstack
  {
    name: 'Netlify',
    logo: 'https://www.netlify.com/img/press/logos/logomark.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'All-in-one platform for automating modern web projects',
  },
  {
    name: 'Vercel',
    logo: 'https://assets.vercel.com/image/upload/q_auto/front/assets/design/vercel-triangle-black.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Platform for static and hybrid applications built to integrate with your headless content, commerce, or database',
  },

  // Design Systems
  {
    name: 'Storybook',
    logo: 'https://storybook.js.org/images/logos/icon-storybook.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Tool for developing UI components in isolation',
  },
  {
    name: 'Styleguidist',
    logo: 'https://react-styleguidist.js.org/img/logo.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Isolated React component development environment with a living style guide',
  },

  // Accessibility
  {
    name: 'Axe',
    logo: 'https://www.deque.com/wp-content/uploads/2020/01/axe-con-logo-1.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Accessibility testing toolkit',
  },
  {
    name: 'ARIA',
    logo: 'https://www.w3.org/WAI/content-images/wai-aria-practices/aria-logo.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Accessible Rich Internet Applications specification',
  },

  // Internationalization
  {
    name: 'react-i18next',
    logo: 'https://react.i18next.com/img/logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Internationalization framework for React / React Native',
  },
  {
    name: 'FormatJS',
    logo: 'https://formatjs.io/img/format-js-logo.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Internationalize your web apps on the client & server',
  },
  // Data Visualization
  {
    name: 'D3.js',
    logo: 'https://d3js.org/logo.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'JavaScript library for producing dynamic, interactive data visualizations',
  },
  {
    name: 'Chart.js',
    logo: 'https://www.chartjs.org/media/logo-title.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple yet flexible JavaScript charting for designers & developers',
  },
  // CSS Frameworks and Methodologies
  {
    name: 'Tachyons',
    logo: 'https://tachyons.io/img/logo.jpg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Functional CSS for humans',
  },
  {
    name: 'Pico.css',
    logo: 'https://picocss.com/favicon.ico',
    category: 'Frontend',
    level: 'Beginner',
    description: 'Minimal CSS Framework for semantic HTML',
  },
  {
    name: 'SMACSS',
    logo: 'https://smacss.com/img/jack-head.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Scalable and Modular Architecture for CSS',
  },
  {
    name: 'BEM',
    logo: 'https://en.bem.info/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Block Element Modifier methodology',
  },
  {
    name: 'CSS-in-JS',
    logo: 'https://miro.medium.com/max/1200/1*yVo5S3olj1pjZWIRGUbOZg.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Styling approach that abstracts CSS to the component level',
  },

  // Build Tools and Module Bundlers
  {
    name: 'Webpack',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Static module bundler for modern JavaScript applications',
  },
  {
    name: 'Rollup',
    logo: 'https://rollupjs.org/favicon.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Module bundler for JavaScript',
  },
  {
    name: 'Parcel',
    logo: 'https://parceljs.org/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Blazing fast, zero configuration web application bundler',
  },
  {
    name: 'Snowpack',
    logo: 'https://www.snowpack.dev/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Lightning-fast frontend build tool, designed for the modern web',
  },

  // State Management
  {
    name: 'XState',
    logo: 'https://xstate.js.org/favicon.ico',
    category: 'Frontend',
    level: 'Advanced',
    description: 'State machines and statecharts for the modern web',
  },
  {
    name: 'Recoil',
    logo: 'https://recoiljs.org/img/favicon.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'State management library for React',
  },
  {
    name: 'Jotai',
    logo: 'https://jotai.org/favicon.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Primitive and flexible state management for React',
  },

  // Testing
  {
    name: 'Jest',
    logo: 'https://jestjs.io/img/favicon/favicon.ico',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Delightful JavaScript Testing Framework',
  },
  {
    name: 'Testing Library',
    logo: 'https://testing-library.com/img/octopus-64x64.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Simple and complete testing utilities for React',
  },
  {
    name: 'Vitest',
    logo: 'https://vitest.dev/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Blazing Fast Unit Test Framework',
  },
  // Performance and Optimization
  {
    name: 'Lighthouse',
    logo: 'https://developers.google.com/web/tools/lighthouse/images/lighthouse-logo.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Automated tool for improving the quality of web pages',
  },
  {
    name: 'Web Vitals',
    logo: 'https://web.dev/vitals/web-vitals.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Essential metrics for a healthy site',
  },
  // CSS and CSS Frameworks
  {
    name: 'CSS',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'Styling language for web documents',
  },
  {
    name: 'Sass',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS preprocessor scripting language',
  },
  {
    name: 'Less',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/less/less-plain-wordmark.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Backwards-compatible language extension for CSS',
  },
  {
    name: 'Tailwind CSS',
    logo: 'https://tailwindcss.com/_next/static/media/tailwindcss-mark.3c5441fc7a190fb1800d4a5c7f07ba4b1345a9c8.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Utility-first CSS framework',
  },
  {
    name: 'Bootstrap',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Popular CSS framework for responsive design',
  },
  {
    name: 'Bulma',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bulma/bulma-plain.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Modern CSS framework based on Flexbox',
  },
  {
    name: 'Styled Components',
    logo: 'https://www.styled-components.com/atom.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS-in-JS library for React',
  },
  {
    name: 'CSS Modules',
    logo: 'https://cdn.jsdelivr.net/gh/css-modules/logos@master/css-modules-logo.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Locally scoped CSS for component-based development',
  },
  {
    name: 'Chakra UI',
    logo: 'https://img.icons8.com/?size=512&id=r9QJ0VFFrn7T&format=png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple, modular and accessible component library for React',
  },
  {
    name: 'Material-UI',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: "React components that implement Google's Material Design",
  },
  {
    name: 'Ant Design',
    logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'A design system for enterprise-level products',
  },
  {
    name: 'Foundation',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/foundation/foundation-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Family of responsive front-end frameworks',
  },
  {
    name: 'Semantic UI',
    logo: 'https://semantic-ui.com/images/logo.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Development framework that helps create beautiful, responsive layouts',
  },
  {
    name: 'Stylus',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/stylus/stylus-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Expressive, dynamic, robust CSS preprocessor',
  },
  {
    name: 'Radix UI',
    logo: 'https://avatars.githubusercontent.com/u/75042455',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Unstyled, accessible components for building high‑quality design systems',
  },
]
