export interface Skill {
  name: string
  logo: string
  category: string
  level: string
  description: string
}

export const suggestedSkills: Skill[] = [
  // Frontend Frameworks and Libraries
  {
    name: 'React',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'JavaScript library for building user interfaces',
  },
  {
    name: 'Angular',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Platform for building web applications',
  },
  {
    name: 'Vue.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Progressive JavaScript framework',
  },
  {
    name: 'Next.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'React framework for production',
  },
  {
    name: 'Svelte',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Compiler for building user interfaces',
  },
  {
    name: 'Redux',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'State management for JavaScript apps',
  },
  {
    name: 'MobX',
    logo: 'https://mobx.js.org/assets/mobx.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple, scalable state management',
  },
  {
    name: 'Nuxt.js',
    logo: 'https://nuxtjs.org/design-kit/colored-logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Vue.js framework for server-side rendering',
  },
  {
    name: 'Ember.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ember/ember-original-wordmark.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Framework for ambitious web developers',
  },
  {
    name: 'Alpine.js',
    logo: 'https://alpinejs.dev/alpine_long.svg',
    category: 'Frontend',
    level: 'Beginner',
    description: 'Lightweight JavaScript framework',
  },
  {
    name: 'Lit',
    logo: 'https://lit.dev/images/flame-favicon.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple library for building web components',
  },
  {
    name: 'Astro',
    logo: 'https://astro.build/assets/press/astro-icon-light.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Static site builder for the modern web',
  },
  {
    name: 'Gatsby',
    logo: 'https://www.gatsbyjs.com/Gatsby-Monogram.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'React-based framework for building websites and apps',
  },
  // New additions
  {
    name: 'shadcn/ui',
    logo: 'https://ui.shadcn.com/favicon.ico',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Re-usable components built using Radix UI and Tailwind CSS',
  },
  {
    name: 'Framer Motion',
    logo: 'https://framerusercontent.com/images/FwGRzdHhlF5dVX3w3adwXRyFz7U.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Production-ready motion library for React',
  },
  {
    name: 'React Hook Form',
    logo: 'https://avatars.githubusercontent.com/u/53986236?s=200&v=4',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Performant, flexible and extensible forms with easy-to-use validation',
  },
  {
    name: 'Zustand',
    logo: 'https://repository-images.githubusercontent.com/180328715/fca49300-e7f1-11ea-9f51-cfd949b31560',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Small, fast and scalable bearbones state-management solution',
  },
  {
    name: 'Storybook',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/storybook/storybook-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Tool for building UI components and pages in isolation',
  },
  {
    name: 'Vite',
    logo: 'https://vitejs.dev/logo.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Next generation frontend tooling',
  },
  {
    name: 'Remix',
    logo: 'https://remix.run/img/og.1.jpg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Full stack web framework based on React',
  },
  {
    name: 'Electron',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Framework for creating native applications with web technologies',
  },
  {
    name: 'jQuery',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Fast, small, and feature-rich JavaScript library',
  },
  {
    name: 'Backbone.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/backbonejs/backbonejs-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Give structure to web applications with models, views, and collections',
  },
  // CSS and CSS Frameworks
  {
    name: 'CSS',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
    category: 'Frontend',
    level: 'Expert',
    description: 'Styling language for web documents',
  },
  {
    name: 'Sass',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS preprocessor scripting language',
  },
  {
    name: 'Less',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/less/less-plain-wordmark.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Backwards-compatible language extension for CSS',
  },
  {
    name: 'Tailwind CSS',
    logo: 'https://tailwindcss.com/_next/static/media/tailwindcss-mark.3c5441fc7a190fb1800d4a5c7f07ba4b1345a9c8.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Utility-first CSS framework',
  },
  {
    name: 'Bootstrap',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Popular CSS framework for responsive design',
  },
  {
    name: 'Bulma',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bulma/bulma-plain.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Modern CSS framework based on Flexbox',
  },
  {
    name: 'Styled Components',
    logo: 'https://www.styled-components.com/atom.png',
    category: 'Frontend',
    level: 'Advanced',
    description: 'CSS-in-JS library for React',
  },
  {
    name: 'CSS Modules',
    logo: 'https://cdn.jsdelivr.net/gh/css-modules/logos@master/css-modules-logo.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Locally scoped CSS for component-based development',
  },
  {
    name: 'Chakra UI',
    logo: 'https://img.icons8.com/?size=512&id=r9QJ0VFFrn7T&format=png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Simple, modular and accessible component library for React',
  },
  {
    name: 'Material-UI',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: "React components that implement Google's Material Design",
  },
  {
    name: 'Ant Design',
    logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
    category: 'Frontend',
    level: 'Advanced',
    description: 'A design system for enterprise-level products',
  },
  {
    name: 'Foundation',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/foundation/foundation-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Family of responsive front-end frameworks',
  },
  {
    name: 'Semantic UI',
    logo: 'https://semantic-ui.com/images/logo.png',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Development framework that helps create beautiful, responsive layouts',
  },
  {
    name: 'Stylus',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/stylus/stylus-original.svg',
    category: 'Frontend',
    level: 'Intermediate',
    description: 'Expressive, dynamic, robust CSS preprocessor',
  },
  {
    name: 'Radix UI',
    logo: 'https://avatars.githubusercontent.com/u/75042455',
    category: 'Frontend',
    level: 'Advanced',
    description: 'Unstyled, accessible components for building high‑quality design systems',
  },
]
